cache:
  # This persistent cache is used to cache the building of
  # docker base images.
  directories:
    - $DOCKER_TRAVIS_CI_CACHE_DIR
sudo: required
language: cpp
services:
  - docker
env:
  global:
    # This environment variable tells the `travis_ci_linux_entry_point.sh`
    # script to look for a cached Docker image.
    - DOCKER_TRAVIS_CI_CACHE_DIR=$HOME/.cache/docker
  # Configurations
  matrix:
###############################################################################
# Ubuntu 16.04 LTS
###############################################################################
    # 64-bit UBSan Debug build
    - LINUX_BASE=ubuntu_16.04 C_COMPILER=/usr/bin/clang-6.0 CXX_COMPILER=/usr/bin/clang++-6.0 TARGET_ARCH=x86_64 Z3_BUILD_TYPE=Debug UBSAN_BUILD=1 RUN_UNIT_TESTS=SKIP
    # 64-bit ASan Debug build
    - LINUX_BASE=ubuntu_16.04 C_COMPILER=/usr/bin/clang-6.0 CXX_COMPILER=/usr/bin/clang++-6.0 TARGET_ARCH=x86_64 Z3_BUILD_TYPE=Debug ASAN_BUILD=1 RUN_UNIT_TESTS=SKIP ASAN_DSO=/usr/lib/clang/6.0/lib/linux/libclang_rt.asan-x86_64.so
    # Build for running unit tests under ASan/UBSan
    # FIXME: We should really be doing a debug build but the unit tests run too
    # slowly when we do that.
    - LINUX_BASE=ubuntu_16.04 C_COMPILER=/usr/bin/clang-6.0 CXX_COMPILER=/usr/bin/clang++-6.0 TARGET_ARCH=x86_64 Z3_BUILD_TYPE=RelWithDebInfo ASAN_BUILD=1 RUN_UNIT_TESTS=BUILD_AND_RUN ASAN_DSO=/usr/lib/clang/6.0/lib/linux/libclang_rt.asan-x86_64.so UBSAN_BUILD=1 RUN_API_EXAMPLES=0 RUN_SYSTEM_TESTS=0 DOTNET_BINDINGS=0 JAVA_BINDINGS=0 PYTHON_BINDINGS=0

# macOS (a.k.a OSX) support
matrix:
  include:
    # For now just test a single configuration. macOS builds on TravisCI are
    # very slow so we should keep the number of configurations we test on this
    # OS to a minimum.
    - os: osx
      osx_image: xcode8.3
      # Note: Apple Clang does not support OpenMP
      env: Z3_BUILD_TYPE=RelWithDebInfo USE_OPENMP=0 DOTNET_BINDINGS=0
script:
  # Use `travis_wait` when doing LTO builds because this configuration will
  # have long link times during which it will not show any output which
  # TravisCI might kill due to perceived inactivity.
  - if [ "X${USE_LTO}" = "X1" ]; then
      travis_wait 45 contrib/ci/scripts/travis_ci_entry_point.sh || exit 1;
    else
      contrib/ci/scripts/travis_ci_entry_point.sh || exit 1;
    fi
